/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface InferusNamesInterface extends utils.Interface {
  contractName: "InferusNames";
  functions: {
    "basePrice()": FunctionFragment;
    "claim(bytes32)": FunctionFragment;
    "getHashForRegisterBySignature(bytes32,address,bytes)": FunctionFragment;
    "getMetadataURI(bytes32)": FunctionFragment;
    "initialize(uint256)": FunctionFragment;
    "linkingPrices(address)": FunctionFragment;
    "metadataURIs(bytes32)": FunctionFragment;
    "names(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "register(bytes32,bytes)": FunctionFragment;
    "registerBySignature(bytes32,address,bytes,bytes)": FunctionFragment;
    "release(bytes32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setBasePrice(uint256)": FunctionFragment;
    "setMetadataURI(bytes32,bytes)": FunctionFragment;
    "totalNames()": FunctionFragment;
    "transfer(bytes32,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transfers(bytes32)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "basePrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "claim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getHashForRegisterBySignature",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMetadataURI",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "linkingPrices",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "metadataURIs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "names", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBySignature",
    values: [BytesLike, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "release", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBasePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetadataURI",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalNames",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transfers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "basePrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHashForRegisterBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "linkingPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metadataURIs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "names", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBasePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalNames", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "MetadataUpdated(bytes32,bytes)": EventFragment;
    "NameRegistered(address,bytes32,bytes)": EventFragment;
    "NameReleased(address,bytes32)": EventFragment;
    "NameTransferCompleted(address,address,bytes32)": EventFragment;
    "NameTransferInitiated(address,address,bytes32)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MetadataUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameReleased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameTransferCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameTransferInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export type AdminChangedEvent = TypedEvent<
  [string, string],
  { previousAdmin: string; newAdmin: string }
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export type BeaconUpgradedEvent = TypedEvent<[string], { beacon: string }>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export type InitializedEvent = TypedEvent<[number], { version: number }>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export type MetadataUpdatedEvent = TypedEvent<
  [string, string],
  { name: string; metadataURI: string }
>;

export type MetadataUpdatedEventFilter = TypedEventFilter<MetadataUpdatedEvent>;

export type NameRegisteredEvent = TypedEvent<
  [string, string, string],
  { registrant: string; name: string; metadataURI: string }
>;

export type NameRegisteredEventFilter = TypedEventFilter<NameRegisteredEvent>;

export type NameReleasedEvent = TypedEvent<
  [string, string],
  { registrant: string; name: string }
>;

export type NameReleasedEventFilter = TypedEventFilter<NameReleasedEvent>;

export type NameTransferCompletedEvent = TypedEvent<
  [string, string, string],
  { from: string; to: string; name: string }
>;

export type NameTransferCompletedEventFilter =
  TypedEventFilter<NameTransferCompletedEvent>;

export type NameTransferInitiatedEvent = TypedEvent<
  [string, string, string],
  { from: string; to: string; name: string }
>;

export type NameTransferInitiatedEventFilter =
  TypedEventFilter<NameTransferInitiatedEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type UpgradedEvent = TypedEvent<[string], { implementation: string }>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface InferusNames extends BaseContract {
  contractName: "InferusNames";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InferusNamesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    basePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    claim(
      _name: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getHashForRegisterBySignature(
      _name: BytesLike,
      _owner: string,
      _metadataURI: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMetadataURI(
      _name: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    linkingPrices(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    metadataURIs(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    names(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    register(
      _name: BytesLike,
      _metadataURI: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerBySignature(
      _name: BytesLike,
      _owner: string,
      _metadataURI: BytesLike,
      _signature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    release(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBasePrice(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMetadataURI(
      _name: BytesLike,
      _uri: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalNames(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      _name: BytesLike,
      _recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transfers(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  basePrice(overrides?: CallOverrides): Promise<BigNumber>;

  claim(
    _name: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getHashForRegisterBySignature(
    _name: BytesLike,
    _owner: string,
    _metadataURI: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getMetadataURI(_name: BytesLike, overrides?: CallOverrides): Promise<string>;

  initialize(
    _basePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  linkingPrices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  metadataURIs(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  names(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  register(
    _name: BytesLike,
    _metadataURI: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerBySignature(
    _name: BytesLike,
    _owner: string,
    _metadataURI: BytesLike,
    _signature: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  release(
    _name: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBasePrice(
    _basePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMetadataURI(
    _name: BytesLike,
    _uri: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalNames(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    _name: BytesLike,
    _recipient: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transfers(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    _amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    basePrice(overrides?: CallOverrides): Promise<BigNumber>;

    claim(_name: BytesLike, overrides?: CallOverrides): Promise<void>;

    getHashForRegisterBySignature(
      _name: BytesLike,
      _owner: string,
      _metadataURI: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getMetadataURI(
      _name: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      _basePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    linkingPrices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    metadataURIs(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    names(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    register(
      _name: BytesLike,
      _metadataURI: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    registerBySignature(
      _name: BytesLike,
      _owner: string,
      _metadataURI: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    release(_name: BytesLike, overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setBasePrice(
      _basePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMetadataURI(
      _name: BytesLike,
      _uri: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    totalNames(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      _name: BytesLike,
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transfers(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(beacon?: string | null): BeaconUpgradedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "MetadataUpdated(bytes32,bytes)"(
      name?: BytesLike | null,
      metadataURI?: null
    ): MetadataUpdatedEventFilter;
    MetadataUpdated(
      name?: BytesLike | null,
      metadataURI?: null
    ): MetadataUpdatedEventFilter;

    "NameRegistered(address,bytes32,bytes)"(
      registrant?: string | null,
      name?: BytesLike | null,
      metadataURI?: null
    ): NameRegisteredEventFilter;
    NameRegistered(
      registrant?: string | null,
      name?: BytesLike | null,
      metadataURI?: null
    ): NameRegisteredEventFilter;

    "NameReleased(address,bytes32)"(
      registrant?: string | null,
      name?: BytesLike | null
    ): NameReleasedEventFilter;
    NameReleased(
      registrant?: string | null,
      name?: BytesLike | null
    ): NameReleasedEventFilter;

    "NameTransferCompleted(address,address,bytes32)"(
      from?: string | null,
      to?: string | null,
      name?: null
    ): NameTransferCompletedEventFilter;
    NameTransferCompleted(
      from?: string | null,
      to?: string | null,
      name?: null
    ): NameTransferCompletedEventFilter;

    "NameTransferInitiated(address,address,bytes32)"(
      from?: string | null,
      to?: string | null,
      name?: null
    ): NameTransferInitiatedEventFilter;
    NameTransferInitiated(
      from?: string | null,
      to?: string | null,
      name?: null
    ): NameTransferInitiatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    basePrice(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      _name: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getHashForRegisterBySignature(
      _name: BytesLike,
      _owner: string,
      _metadataURI: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMetadataURI(
      _name: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    linkingPrices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    metadataURIs(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    names(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    register(
      _name: BytesLike,
      _metadataURI: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerBySignature(
      _name: BytesLike,
      _owner: string,
      _metadataURI: BytesLike,
      _signature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    release(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBasePrice(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMetadataURI(
      _name: BytesLike,
      _uri: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalNames(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      _name: BytesLike,
      _recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transfers(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    basePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claim(
      _name: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getHashForRegisterBySignature(
      _name: BytesLike,
      _owner: string,
      _metadataURI: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMetadataURI(
      _name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    linkingPrices(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metadataURIs(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    names(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    register(
      _name: BytesLike,
      _metadataURI: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerBySignature(
      _name: BytesLike,
      _owner: string,
      _metadataURI: BytesLike,
      _signature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    release(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBasePrice(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMetadataURI(
      _name: BytesLike,
      _uri: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalNames(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      _name: BytesLike,
      _recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transfers(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
